--- connectivity/source/drivers/kab/KResultSet.cxx.old	2005-09-22 14:15:29.000000000 +0200
+++ connectivity/source/drivers/kab/KResultSet.cxx	2005-09-22 14:22:01.000000000 +0200
@@ -201,6 +201,8 @@
 	::dbtools::throwGenericSQLException(
 		::rtl::OUString::createFromAscii("Invalid column name: ") + columnName,
 		NULL);
+	// just to avoid warning: control reaches end of non-void function
+	return 1;
 }
 // -------------------------------------------------------------------------
 Reference< XInputStream > SAL_CALL KabResultSet::getBinaryStream(sal_Int32 columnIndex) throw(SQLException, RuntimeException)
--- connectivity/source/drivers/kab/KStatement.cxx.orig	2005-12-19 17:51:20.000000000 +0100
+++ connectivity/source/drivers/kab/KStatement.cxx	2006-01-05 11:00:50.000000000 +0100
@@ -214,6 +214,8 @@
 	::dbtools::throwGenericSQLException(
 		::rtl::OUString::createFromAscii("Syntax error or keyword not recognized."),
 		NULL);
+	// just to avoid warning: control reaches end of non-void function
+	return NULL;
 }
 // -----------------------------------------------------------------------------
 KabOrder *KabCommonStatement::analyseOrderByClause(const OSQLParseNode *pParseNode) const throw(SQLException)
@@ -261,6 +263,8 @@
 	::dbtools::throwGenericSQLException(
 		::rtl::OUString::createFromAscii("Syntax error or keyword not recognized."),
 		NULL);
+	// just to avoid warning: control reaches end of non-void function
+	return NULL;
 }
 //------------------------------------------------------------------------------
 sal_Bool KabCommonStatement::isTableKnown(KabResultSet *pResult) const
--- connectivity/source/drivers/kab/kfields.cxx.old	2005-12-19 17:53:21.000000000 +0100
+++ connectivity/source/drivers/kab/kfields.cxx	2006-01-05 11:09:50.000000000 +0100
@@ -85,6 +85,10 @@
 	::dbtools::throwGenericSQLException(
 		::rtl::OUString::createFromAscii("Invalid column name: ") + columnName,
 		NULL);
+	// just to avoid warning: control reaches end of non-void function in a broken gcc-4.1
+	// this code is never accessed because of the throw*Exception above
+	return 0;                                                               
+
 }
 // ------------------------------------------------------------------------------
 	}
